name: Daily newsletter workflow

on:
  schedule:
    # Send the newsletter daily at 6:30 am.
    - cron: '30 6 * * *'
  workflow_dispatch:

jobs:
  Query-And-Notification:
    runs-on: ubuntu-latest
    environment: news
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv pandas openai selenium chromedriver-autoinstaller pyvirtualdisplay pipenv
          pipenv install

      - name: Send the newsletter to the subscribers
        env:
          GMAIL_USERNAME: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pipenv run python newsletter.py
